### ISSUE TITLE
ERROR Altay 3.0.6

### ISSUE THREAD

**Issue by ghost** [hikingjungle/PM-Lightning-plugin#1]
ERROR > 폴더 'C:\Users\ghkst\Desktop\Altay-master\plugins\'에서 'C:\Users\ghkst\Desktop\Altay-master\plugins\PM-Lightning-plugin-master'을(를) 불러올 수 없습니다: yaml_parse(): scanning error encountered during parsing: found unexpected document indicator (line 11, column 1), context while scanning a quoted scalar (line 4, column 10)
16:49:15 CRITICAL > ErrorException: "yaml_parse(): scanning error encountered during parsing: found unexpected document indicator (line 11, column 1), context while scanning a quoted scalar (line 4, column 10)" (EXCEPTION) in "src/pocketmine/plugin/PluginDescription" at line 62
16:49:15 DEBUG > #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string yaml_parse(): scanning error encountered during parsing: found unexpected document indicator (line 11, column 1), context while scanning a quoted scalar (line 4, column 10), string phar://C:/Users/ghkst/Desktop/Altay-master/Altay.phar/src/pocketmine/plugin/PluginDescription.php, integer 62, array Array())
16:49:15 DEBUG > #1 src/pocketmine/plugin/PluginDescription(62): yaml_parse(string ---..name: Lightning Strike..main: LightningStrike\LightningStrike..version: "2.0..api:..- 3.0.0-ALPHA12..- 3.0.0..load: STARTUP..author: MichaelM04..description: Strikes Lightning On Ground When A Player  Dies,Joins,Quits.......)
16:49:15 DEBUG > #2 src/pocketmine/plugin/FolderPluginLoader(60): pocketmine\plugin\PluginDescription->__construct(string ---..name: Lightning Strike..main: LightningStrike\LightningStrike..version: "2.0..api:..- 3.0.0-ALPHA12..- 3.0.0..load: STARTUP..author: MichaelM04..description: Strikes Lightning On Ground When A Player  Dies,Joins,Quits.......)
16:49:15 DEBUG > #3 src/pocketmine/plugin/PluginManager(257): pocketmine\plugin\FolderPluginLoader->getPluginDescription(string C:\Users\ghkst\Desktop\Altay-master\plugins\PM-Lightning-plugin-master)
16:49:15 DEBUG > #4 src/pocketmine/Server(1705): pocketmine\plugin\PluginManager->loadPlugins(string C:\Users\ghkst\Desktop\Altay-master\plugins\)
16:49:15 DEBUG > #5 src/pocketmine/PocketMine(241): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\ghkst\Desktop\Altay-master\, string C:\Users\ghkst\Desktop\Altay-master\plugins\)
16:49:15 DEBUG > #6 C:/Users/ghkst/Desktop/Altay-master/Altay.phar(1): require_once(string phar://C:/Users/ghkst/Desktop/Altay-master/Altay.phar/src/pocketmine/PocketMine.php)

**Comment by hikingjungle** [comment]
this plugin only officially supports pmmp
